export const GAME_ACTIONS = {
  SET_TIMER: 'SET_TIMER',
  REDUCE_TIME: 'REDUCE_TIME',
  REFRESH_GAME: 'REFRESH_GAME',
  START_GAME: 'START_GAME',
  END_GAME: 'END_GAME',
  SET_START: 'SET_START',
  SET_IN_PROGRESS: 'SET_IN_PROGRESS',
  SET_END: 'SET_END',
  NEW_PROMPT: 'NEW_PROMPT',
  SET_PROMPT: 'SET_PROMPT',
};